version: '3'

services:
  web-app:
    container_name: "${COMPOSE_NAME}-web-app"
    image: "$FLASK_BUILD_NAME"
    deploy:
        restart_policy:
            condition: on-failure
            max_attempts: 3
            # delay: 5s  - only work with orchestrators not compose
            # window: 120s - only work with orchestrators not compose    
    ports:
      - "5000:5000"
    environment:
      DB_USER: idubi
      DB_PASSWORD: idubi
      DB_NAME: idubi
      DB_TYPE: postgresql
      DB_HOST: postgres-db
      DB_PORT: 5432
    depends_on:
      - postgres-db
    restart: On-failure
    networks:
      - flask-ntwrk
  postgres-db:
    container_name: "${COMPOSE_NAME}-postgres-db"
    image: postgres
    environment:
      POSTGRES_USER: idubi
      POSTGRES_PASSWORD: idubi
      POSTGRES_DB: idubi
    ports:
      - "5432:5432"
    networks:
      - flask-ntwrk   
networks:
  flask-ntwrk:
    driver: bridge




# healthcheck:
#       test: ["CMD-SHELL", "PGPASSWORD=idubi psql -U idubi -d idubi -c 'SELECT 1 FROM user LIMIT 1;' > /dev/null || exit 1"]
#       interval: 30s
#       timeout: 15s
#       retries: 5

# networks:
#   - app-network
# networks:
#   app-network:

    # networks:
    #   - app-network
